export const quizQuestions = [
  {
    id: 1,
    question: "When facing a challenge, what's your first instinct?",
    description: 'Think about how you naturally respond to obstacles.',
    answers: [
      {
        id: 'a',
        text: 'Take immediate action',
        description: 'Jump in headfirst and figure it out as you go',
        icon: '⚡',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Reflect and feel it out',
        description: 'Trust your intuition and emotional response',
        icon: '🌙',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Make a practical plan',
        description: 'Break it down into manageable steps',
        icon: '📋',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Research and analyze',
        description: 'Gather information and consider all options',
        icon: '🔍',
        element: 'air',
      },
    ],
  },
  {
    id: 2,
    question: 'Which environment makes you feel most alive?',
    answers: [
      {
        id: 'a',
        text: 'A bustling city center',
        description: 'Energy, excitement, and constant movement',
        icon: '🏙️',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'By the ocean or lake',
        description: 'Peaceful waters and flowing energy',
        icon: '🌊',
        element: 'water',
      },
      {
        id: 'c',
        text: 'In a forest or garden',
        description: "Grounded in nature's stability",
        icon: '🌲',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'On a mountain peak',
        description: 'High above with endless views',
        icon: '⛰️',
        element: 'air',
      },
    ],
  },
  {
    id: 3,
    question: 'How do you prefer to recharge your energy?',
    answers: [
      {
        id: 'a',
        text: 'Physical activity or adventure',
        description: 'Moving your body and seeking thrills',
        icon: '🏃',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Meditation or quiet reflection',
        description: 'Going inward and connecting with feelings',
        icon: '🧘',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Hands-on activities or crafts',
        description: 'Creating something tangible with your hands',
        icon: '🛠️',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Reading or learning something new',
        description: 'Feeding your mind with fresh ideas',
        icon: '📚',
        element: 'air',
      },
    ],
  },
  {
    id: 4,
    question: "What's your approach to making decisions?",
    answers: [
      {
        id: 'a',
        text: 'Go with your gut instinct',
        description: 'Trust your immediate impulse',
        icon: '💫',
        element: 'fire',
      },
      {
        id: 'b',
        text: "Feel what's right in your heart",
        description: 'Let emotions guide your choice',
        icon: '💖',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Consider practical consequences',
        description: 'Think about real-world outcomes',
        icon: '⚖️',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Analyze pros and cons logically',
        description: 'Use reason and systematic thinking',
        icon: '🧠',
        element: 'air',
      },
    ],
  },
  {
    id: 5,
    question: 'Which crystal calls to you most?',
    answers: [
      {
        id: 'a',
        text: 'Ruby - Stone of passion',
        description: 'Ignites courage and vitality',
        icon: '💎',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Moonstone - Stone of intuition',
        description: 'Enhances emotional wisdom',
        icon: '🌙',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Green Aventurine - Stone of growth',
        description: 'Promotes stability and prosperity',
        icon: '🍀',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Clear Quartz - Stone of clarity',
        description: 'Amplifies mental focus and communication',
        icon: '💠',
        element: 'air',
      },
    ],
  },
  {
    id: 6,
    question: 'How do you handle stress?',
    answers: [
      {
        id: 'a',
        text: 'Channel it into action',
        description: 'Use the energy to tackle problems head-on',
        icon: '🔥',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Process emotions deeply',
        description: 'Feel through it and seek emotional release',
        icon: '🌊',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Focus on practical solutions',
        description: 'Break problems into manageable pieces',
        icon: '🔧',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Talk it out or write about it',
        description: 'Process through communication and analysis',
        icon: '💬',
        element: 'air',
      },
    ],
  },
  {
    id: 7,
    question: 'What type of movie draws you in?',
    answers: [
      {
        id: 'a',
        text: 'Action-packed adventures',
        description: 'High energy and thrilling sequences',
        icon: '🎬',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Emotional dramas',
        description: 'Deep character development and feelings',
        icon: '🎭',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Realistic stories',
        description: 'Grounded narratives about real life',
        icon: '🎪',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Sci-fi or mysteries',
        description: 'Complex plots that challenge your mind',
        icon: '🚀',
        element: 'air',
      },
    ],
  },
  {
    id: 8,
    question: 'Which season resonates with your soul?',
    answers: [
      {
        id: 'a',
        text: 'Summer - Vibrant and energetic',
        description: 'Long days, warmth, and endless possibilities',
        icon: '☀️',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Autumn - Reflective and transformative',
        description: 'Time for introspection and emotional depth',
        icon: '🍂',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Spring - Growth and renewal',
        description: 'Fresh beginnings and steady progress',
        icon: '🌸',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Winter - Clear and contemplative',
        description: 'Crisp air and mental clarity',
        icon: '❄️',
        element: 'air',
      },
    ],
  },
  {
    id: 9,
    question: "What's your ideal way to spend a weekend?",
    answers: [
      {
        id: 'a',
        text: 'Trying something new and exciting',
        description: 'Adventure, spontaneity, and high energy',
        icon: '🎢',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Connecting deeply with loved ones',
        description: 'Meaningful conversations and emotional bonding',
        icon: '👥',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Working on a personal project',
        description: 'Building, creating, or organizing something',
        icon: '🔨',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Exploring ideas and concepts',
        description: 'Learning, discussing, and mental stimulation',
        icon: '💡',
        element: 'air',
      },
    ],
  },
  {
    id: 10,
    question: 'Which element in nature speaks to you?',
    answers: [
      {
        id: 'a',
        text: 'Lightning during a storm',
        description: 'Raw power and electric energy',
        icon: '⚡',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Gentle rain on leaves',
        description: 'Soothing, nurturing, and cleansing',
        icon: '🌧️',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Ancient trees with deep roots',
        description: 'Stability, wisdom, and endurance',
        icon: '🌳',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Wind moving through open spaces',
        description: 'Freedom, movement, and endless possibilities',
        icon: '💨',
        element: 'air',
      },
    ],
  },
  {
    id: 11,
    question: 'How do you express creativity?',
    answers: [
      {
        id: 'a',
        text: 'Bold, dramatic expressions',
        description: 'Bright colors, dynamic movement, and passion',
        icon: '🎨',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Emotional and intuitive art',
        description: 'From the heart, flowing and organic',
        icon: '🎵',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Practical and functional creations',
        description: 'Beautiful things that serve a purpose',
        icon: '🏺',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Conceptual and intellectual works',
        description: 'Ideas that challenge and inspire thinking',
        icon: '✍️',
        element: 'air',
      },
    ],
  },
  {
    id: 12,
    question: 'What motivates you most in life?',
    answers: [
      {
        id: 'a',
        text: 'Achievement and recognition',
        description: 'Being seen for your accomplishments',
        icon: '🏆',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Deep connections and love',
        description: 'Meaningful relationships and emotional fulfillment',
        icon: '💕',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Security and stability',
        description: 'Building a solid foundation for the future',
        icon: '🏠',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Knowledge and understanding',
        description: 'Learning and sharing wisdom with others',
        icon: '🎓',
        element: 'air',
      },
    ],
  },
  {
    id: 13,
    question: 'Which tarot archetype resonates with you?',
    answers: [
      {
        id: 'a',
        text: 'The Magician - Manifestation',
        description: 'Turning ideas into reality through will',
        icon: '🪄',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'The High Priestess - Intuition',
        description: 'Deep wisdom and psychic knowing',
        icon: '🔮',
        element: 'water',
      },
      {
        id: 'c',
        text: 'The Empress - Nurturing',
        description: 'Abundance, growth, and material comfort',
        icon: '👑',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'The Hermit - Seeking truth',
        description: 'Inner wisdom and spiritual guidance',
        icon: '🕯️',
        element: 'air',
      },
    ],
  },
  {
    id: 14,
    question: 'How do you approach new relationships?',
    answers: [
      {
        id: 'a',
        text: 'Dive in with enthusiasm',
        description: 'Open, direct, and passionate from the start',
        icon: '💥',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Build trust slowly and deeply',
        description: 'Allow emotional intimacy to develop naturally',
        icon: '🌱',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Take time to assess compatibility',
        description: 'Look for shared values and long-term potential',
        icon: '🤝',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Connect through shared interests',
        description: 'Bond over ideas, conversations, and mental stimulation',
        icon: '🗣️',
        element: 'air',
      },
    ],
  },
  {
    id: 15,
    question: "What's your relationship with time?",
    answers: [
      {
        id: 'a',
        text: 'Live in the moment intensely',
        description: 'Present-focused with bursts of activity',
        icon: '⏰',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Flow with natural rhythms',
        description: 'Intuitive timing based on feelings',
        icon: '🌊',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Plan and structure carefully',
        description: 'Organized approach with long-term thinking',
        icon: '📅',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'See time as flexible and conceptual',
        description: 'Mental focus can make time seem to expand or contract',
        icon: '⌛',
        element: 'air',
      },
    ],
  },
  {
    id: 16,
    question: 'Which color palette draws you in?',
    answers: [
      {
        id: 'a',
        text: 'Warm reds, oranges, and golds',
        description: 'Vibrant, energizing, and bold',
        icon: '🔴',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Cool blues, silvers, and purples',
        description: 'Soothing, mysterious, and emotional',
        icon: '🔵',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Earth tones, greens, and browns',
        description: 'Natural, grounding, and harmonious',
        icon: '🟢',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Bright yellows, whites, and pastels',
        description: 'Light, airy, and intellectually stimulating',
        icon: '🟡',
        element: 'air',
      },
    ],
  },
  {
    id: 17,
    question: "What's your ideal learning style?",
    answers: [
      {
        id: 'a',
        text: 'Hands-on experience and trial',
        description: 'Learn by doing and making mistakes',
        icon: '👐',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Emotional connection and stories',
        description: 'Learn through feeling and personal meaning',
        icon: '📖',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Step-by-step structured approach',
        description: 'Build knowledge systematically and practically',
        icon: '📊',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Discussion and mental exploration',
        description: 'Learn through dialogue and conceptual thinking',
        icon: '💭',
        element: 'air',
      },
    ],
  },
  {
    id: 18,
    question: 'How do you handle conflict?',
    answers: [
      {
        id: 'a',
        text: 'Address it directly and quickly',
        description: 'Confront issues head-on with energy',
        icon: '⚔️',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Seek emotional understanding',
        description: 'Try to feel and heal the underlying hurt',
        icon: '🕊️',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Find practical compromises',
        description: 'Look for realistic solutions that work',
        icon: '🤲',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Analyze and communicate clearly',
        description: 'Use logic and discussion to resolve issues',
        icon: '💬',
        element: 'air',
      },
    ],
  },
  {
    id: 19,
    question: "What's your relationship with change?",
    answers: [
      {
        id: 'a',
        text: 'Embrace it as adventure',
        description: 'See change as exciting opportunities',
        icon: '🎯',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Feel through the emotions it brings',
        description: 'Process change through your heart',
        icon: '🌀',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Prefer gradual, planned transitions',
        description: "Like change that's steady and purposeful",
        icon: '🐌',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Adapt quickly with mental flexibility',
        description: 'Use your mind to navigate new situations',
        icon: '🦋',
        element: 'air',
      },
    ],
  },
  {
    id: 20,
    question: 'Which spiritual practice calls to you?',
    answers: [
      {
        id: 'a',
        text: 'Dynamic movement and ritual',
        description: 'Active practices that build energy',
        icon: '🕺',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Meditation and emotional healing',
        description: 'Practices that connect you to your inner world',
        icon: '🧘‍♀️',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Nature connection and grounding',
        description: 'Earth-based practices and natural rhythms',
        icon: '🌿',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Study and philosophical exploration',
        description: 'Mental practices and wisdom traditions',
        icon: '📜',
        element: 'air',
      },
    ],
  },
  {
    id: 21,
    question: "What's your ideal work environment?",
    answers: [
      {
        id: 'a',
        text: 'Fast-paced and competitive',
        description: 'High energy with opportunities to lead',
        icon: '🏃‍♂️',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Collaborative and supportive',
        description: 'Emotionally nurturing with meaningful connections',
        icon: '🤗',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Stable and well-organized',
        description: 'Clear structure with practical goals',
        icon: '🏢',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Intellectually stimulating and flexible',
        description: 'Mental challenges with freedom to innovate',
        icon: '💻',
        element: 'air',
      },
    ],
  },
  {
    id: 22,
    question: 'How do you celebrate achievements?',
    answers: [
      {
        id: 'a',
        text: 'Big, bold celebrations',
        description: 'Party hard and share your success',
        icon: '🎉',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Intimate moments with loved ones',
        description: 'Share the joy with those closest to you',
        icon: '🥂',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Practical rewards and planning ahead',
        description: 'Treat yourself and set new goals',
        icon: '🎁',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Reflect on the learning and growth',
        description: 'Appreciate the knowledge gained',
        icon: '📝',
        element: 'air',
      },
    ],
  },
  {
    id: 23,
    question: "What's your approach to personal growth?",
    answers: [
      {
        id: 'a',
        text: 'Push boundaries and take risks',
        description: 'Grow through challenges and bold action',
        icon: '🚀',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Explore emotions and inner wisdom',
        description: 'Grow through self-reflection and feeling',
        icon: '🪞',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Build skills and habits gradually',
        description: 'Grow through consistent, practical steps',
        icon: '🪜',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Study, learn, and expand perspectives',
        description: 'Grow through knowledge and understanding',
        icon: '🌐',
        element: 'air',
      },
    ],
  },
  {
    id: 24,
    question: 'Which life philosophy resonates most?',
    answers: [
      {
        id: 'a',
        text: "'Life is meant to be lived boldly'",
        description: 'Embrace passion and take decisive action',
        icon: '⭐',
        element: 'fire',
      },
      {
        id: 'b',
        text: "'Follow your heart and trust your feelings'",
        description: 'Let intuition and emotion guide your path',
        icon: '💫',
        element: 'water',
      },
      {
        id: 'c',
        text: "'Slow and steady wins the race'",
        description: 'Build a solid foundation through patience',
        icon: '🐢',
        element: 'earth',
      },
      {
        id: 'd',
        text: "'Knowledge is power and freedom'",
        description: 'Understanding leads to liberation',
        icon: '🦉',
        element: 'air',
      },
    ],
  },
  {
    id: 25,
    question: 'What legacy do you want to leave?',
    answers: [
      {
        id: 'a',
        text: 'Inspiring others to be brave',
        description: 'Be remembered for courage and leadership',
        icon: '🔥',
        element: 'fire',
      },
      {
        id: 'b',
        text: 'Healing and nurturing others',
        description: 'Be remembered for compassion and emotional support',
        icon: '💧',
        element: 'water',
      },
      {
        id: 'c',
        text: 'Building something lasting and meaningful',
        description: 'Be remembered for practical contributions',
        icon: '🌍',
        element: 'earth',
      },
      {
        id: 'd',
        text: 'Sharing wisdom and expanding minds',
        description: 'Be remembered for intellectual contributions',
        icon: '🌬️',
        element: 'air',
      },
    ],
  },
]
