export const quizQuestions = [
  {
    id: 1,
    type: 'emotion',
    question:
      'When you think of your last romantic connection, what emotion surfaces strongest?',
    subtitle: 'Your emotional landscape reveals readiness for new love',
    options: [
      {
        id: 'gratitude',
        text: 'Gratitude and peaceful closure',
        description: "You've processed the experience with wisdom",
        icon: '🙏',
      },
      {
        id: 'excitement',
        text: "Excitement for what's ahead",
        description: 'Your heart is open and optimistic',
        icon: '✨',
      },
      {
        id: 'sadness',
        text: 'Lingering sadness or longing',
        description: 'Some healing may still be needed',
        icon: '💙',
      },
      {
        id: 'curiosity',
        text: 'Curious about lessons learned',
        description: "You're growing through reflection",
        icon: '🤔',
      },
    ],
  },
  {
    id: 2,
    type: 'astrology',
    question: 'Which celestial moment feels most magnetic to you right now?',
    subtitle: 'The cosmos speaks through your intuitive attractions',
    options: [
      {
        id: 'full_moon',
        text: 'Full moon illuminating the night',
        description: 'Peak emotional clarity and manifestation',
        icon: '🌕',
      },
      {
        id: 'sunrise',
        text: 'Golden sunrise breaking the horizon',
        description: 'New beginnings and fresh starts',
        icon: '🌅',
      },
      {
        id: 'starry_night',
        text: 'Infinite stars in velvet darkness',
        description: 'Mystery and cosmic connection',
        icon: '⭐',
      },
      {
        id: 'sunset',
        text: 'Romantic sunset painting the sky',
        description: 'Completion and beautiful transitions',
        icon: '🌇',
      },
    ],
  },
  {
    id: 3,
    type: 'intuition',
    question: 'In your dreams lately, love appears as...',
    subtitle: 'Your subconscious reveals hidden truths about romantic timing',
    options: [
      {
        id: 'familiar_stranger',
        text: 'A familiar stranger with kind eyes',
        description: 'Soul recognition is near',
        icon: '👁️',
      },
      {
        id: 'warm_embrace',
        text: 'A warm, safe embrace',
        description: 'You crave emotional security',
        icon: '🤗',
      },
      {
        id: 'adventure',
        text: 'Exciting adventures together',
        description: "You're ready for passionate experiences",
        icon: '🌟',
      },
      {
        id: 'peaceful_moments',
        text: 'Quiet, peaceful moments of connection',
        description: 'Deep intimacy calls to you',
        icon: '🕊️',
      },
    ],
  },
  {
    id: 4,
    type: 'timing',
    question: 'Which season makes your heart feel most alive and hopeful?',
    subtitle: 'Seasonal energies align with your romantic cycles',
    options: [
      {
        id: 'spring',
        text: 'Spring - renewal and blooming',
        description: 'Fresh starts and new growth',
        icon: '🌸',
      },
      {
        id: 'summer',
        text: 'Summer - passion and abundance',
        description: 'Peak energy and vibrant connections',
        icon: '☀️',
      },
      {
        id: 'autumn',
        text: 'Autumn - transformation and depth',
        description: 'Meaningful change and maturity',
        icon: '🍂',
      },
      {
        id: 'winter',
        text: 'Winter - introspection and cozy intimacy',
        description: 'Deep bonding and inner reflection',
        icon: '❄️',
      },
    ],
  },
  {
    id: 5,
    type: 'emotion',
    question: 'How do you feel when you see couples deeply in love?',
    subtitle: "Your reaction reveals your heart's readiness",
    options: [
      {
        id: 'inspired',
        text: 'Inspired and hopeful',
        description: "You're aligned with love energy",
        icon: '💖',
      },
      {
        id: 'happy_for_them',
        text: 'Genuinely happy for them',
        description: 'Your heart is open and generous',
        icon: '😊',
      },
      {
        id: 'longing',
        text: 'A sweet longing awakens',
        description: "You're ready to attract love",
        icon: '💭',
      },
      {
        id: 'neutral',
        text: 'Peaceful and neutral',
        description: "You're content and centered",
        icon: '🧘',
      },
    ],
  },
  {
    id: 6,
    type: 'astrology',
    question: 'Which mystical symbol calls to your soul?',
    subtitle: 'Ancient symbols reveal your love archetype',
    options: [
      {
        id: 'infinity',
        text: 'Infinity symbol - eternal connection',
        description: 'You seek timeless, boundless love',
        icon: '∞',
      },
      {
        id: 'heart',
        text: 'Sacred heart - pure devotion',
        description: 'Deep emotional connection is your path',
        icon: '💝',
      },
      {
        id: 'key',
        text: 'Golden key - unlocking mysteries',
        description: "You're ready to discover hidden depths",
        icon: '🗝️',
      },
      {
        id: 'phoenix',
        text: 'Phoenix - rebirth and transformation',
        description: 'Love will transform you completely',
        icon: '🔥',
      },
    ],
  },
  {
    id: 7,
    type: 'timing',
    question: 'During which lunar phase do you feel most romantically charged?',
    subtitle: 'Moon cycles influence your love magnetism',
    options: [
      {
        id: 'new_moon',
        text: 'New Moon - fresh intentions',
        description: 'Perfect for manifesting new love',
        icon: '🌑',
      },
      {
        id: 'waxing_moon',
        text: 'Waxing Moon - building energy',
        description: 'Growing attraction and connection',
        icon: '🌓',
      },
      {
        id: 'full_moon',
        text: 'Full Moon - peak intensity',
        description: 'Maximum emotional and romantic power',
        icon: '🌕',
      },
      {
        id: 'waning_moon',
        text: 'Waning Moon - releasing and healing',
        description: 'Clearing space for new love',
        icon: '🌗',
      },
    ],
  },
  {
    id: 8,
    type: 'emotion',
    question: 'What does your ideal first meeting feel like?',
    subtitle: 'Your vision shapes your romantic reality',
    options: [
      {
        id: 'instant_recognition',
        text: 'Instant soul recognition',
        description: 'Deep knowing and familiarity',
        icon: '⚡',
      },
      {
        id: 'comfortable_ease',
        text: 'Comfortable, natural ease',
        description: 'Effortless connection and flow',
        icon: '🌊',
      },
      {
        id: 'exciting_spark',
        text: 'Exciting spark and chemistry',
        description: 'Electric attraction and passion',
        icon: '✨',
      },
      {
        id: 'gentle_warmth',
        text: 'Gentle warmth and safety',
        description: 'Nurturing and protective energy',
        icon: '🤲',
      },
    ],
  },
  {
    id: 9,
    type: 'astrology',
    question:
      'Which element resonates most with your romantic energy right now?',
    subtitle: 'Elemental forces guide your love journey',
    options: [
      {
        id: 'fire',
        text: 'Fire - passion and adventure',
        description: 'Bold, exciting, transformative love',
        icon: '🔥',
      },
      {
        id: 'earth',
        text: 'Earth - stability and growth',
        description: 'Grounded, nurturing, lasting connection',
        icon: '🌱',
      },
      {
        id: 'air',
        text: 'Air - communication and freedom',
        description: 'Intellectual, inspiring, liberating love',
        icon: '💨',
      },
      {
        id: 'water',
        text: 'Water - emotion and intuition',
        description: 'Deep, healing, spiritually connected love',
        icon: '🌊',
      },
    ],
  },
  {
    id: 10,
    type: 'intuition',
    question: 'When you close your eyes and think of love, what color appears?',
    subtitle: "Colors reveal your heart's frequency",
    options: [
      {
        id: 'golden',
        text: 'Warm golden light',
        description: 'Divine love and spiritual connection',
        icon: '✨',
      },
      {
        id: 'rose',
        text: 'Soft rose pink',
        description: 'Gentle, nurturing, unconditional love',
        icon: '🌹',
      },
      {
        id: 'emerald',
        text: 'Deep emerald green',
        description: 'Heart-centered, healing love',
        icon: '💚',
      },
      {
        id: 'sapphire',
        text: 'Royal sapphire blue',
        description: 'Loyal, trustworthy, eternal love',
        icon: '💙',
      },
    ],
  },
  {
    id: 11,
    type: 'timing',
    question: 'Which time of day feels most romantic to you?',
    subtitle: 'Daily rhythms influence your love magnetism',
    options: [
      {
        id: 'dawn',
        text: 'Dawn - fresh beginnings',
        description: 'New love emerging with the light',
        icon: '🌅',
      },
      {
        id: 'midday',
        text: 'Midday - full radiance',
        description: 'Love in its full glory and power',
        icon: '☀️',
      },
      {
        id: 'twilight',
        text: 'Twilight - magical transitions',
        description: 'Mystical, transformative connections',
        icon: '🌆',
      },
      {
        id: 'midnight',
        text: 'Midnight - intimate mysteries',
        description: 'Deep, soulful, private bonding',
        icon: '🌙',
      },
    ],
  },
  {
    id: 12,
    type: 'emotion',
    question: 'How do you handle romantic disappointments?',
    subtitle: 'Your resilience patterns affect love timing',
    options: [
      {
        id: 'learn_grow',
        text: 'Learn, grow, and trust the process',
        description: 'Wisdom and emotional maturity',
        icon: '🌱',
      },
      {
        id: 'feel_release',
        text: 'Feel fully, then release with grace',
        description: 'Healthy emotional processing',
        icon: '🕊️',
      },
      {
        id: 'seek_support',
        text: 'Seek support and practice self-care',
        description: 'Strong support systems and self-love',
        icon: '🤗',
      },
      {
        id: 'trust_timing',
        text: 'Trust that timing is everything',
        description: 'Faith in divine timing and purpose',
        icon: '⏰',
      },
    ],
  },
  {
    id: 13,
    type: 'astrology',
    question: 'Which planetary energy do you feel most connected to?',
    subtitle: 'Planetary influences shape your romantic destiny',
    options: [
      {
        id: 'venus',
        text: 'Venus - love and beauty',
        description: 'Harmony, attraction, and aesthetic pleasure',
        icon: '♀️',
      },
      {
        id: 'mars',
        text: 'Mars - passion and action',
        description: 'Dynamic energy and bold pursuit',
        icon: '♂️',
      },
      {
        id: 'moon',
        text: 'Moon - intuition and emotion',
        description: 'Deep feelings and psychic connection',
        icon: '🌙',
      },
      {
        id: 'jupiter',
        text: 'Jupiter - expansion and wisdom',
        description: 'Growth, adventure, and higher purpose',
        icon: '♃',
      },
    ],
  },
  {
    id: 14,
    type: 'intuition',
    question: 'In meditation or quiet moments, love feels...',
    subtitle: "Your inner knowing reveals love's approach",
    options: [
      {
        id: 'approaching',
        text: 'Close and approaching',
        description: 'Love is near and coming soon',
        icon: '🚶',
      },
      {
        id: 'present',
        text: 'Already present, waiting to be recognized',
        description: 'Love may already be in your life',
        icon: '👀',
      },
      {
        id: 'growing',
        text: 'Growing and building in the distance',
        description: 'Love is developing gradually',
        icon: '🌱',
      },
      {
        id: 'transforming',
        text: 'Transforming you from within',
        description: "You're becoming ready for love",
        icon: '🦋',
      },
    ],
  },
  {
    id: 15,
    type: 'timing',
    question: 'Which life transition period has brought you the most growth?',
    subtitle: 'Growth cycles predict your next romantic chapter',
    options: [
      {
        id: 'career_change',
        text: 'Career or life purpose shifts',
        description: 'Professional growth opens heart pathways',
        icon: '💼',
      },
      {
        id: 'moving',
        text: 'Moving or changing environments',
        description: 'New places bring new connections',
        icon: '🏠',
      },
      {
        id: 'healing',
        text: 'Healing and personal development',
        description: 'Inner work attracts aligned love',
        icon: '🌿',
      },
      {
        id: 'creative',
        text: 'Creative or spiritual awakening',
        description: 'Artistic expression opens the heart',
        icon: '🎨',
      },
    ],
  },
  {
    id: 16,
    type: 'emotion',
    question:
      'What aspect of yourself are you most excited to share with a partner?',
    subtitle: 'Your authentic self magnetizes true love',
    options: [
      {
        id: 'dreams',
        text: 'Your dreams and aspirations',
        description: 'Vision and purpose attract aligned souls',
        icon: '🌟',
      },
      {
        id: 'humor',
        text: 'Your sense of humor and joy',
        description: 'Laughter creates deep connection',
        icon: '😄',
      },
      {
        id: 'wisdom',
        text: 'Your wisdom and life experiences',
        description: 'Depth and insight attract mature love',
        icon: '🦉',
      },
      {
        id: 'creativity',
        text: 'Your creative and artistic side',
        description: 'Creative expression attracts kindred spirits',
        icon: '🎭',
      },
    ],
  },
  {
    id: 17,
    type: 'astrology',
    question:
      'Which cosmic event would you most like to experience with your future love?',
    subtitle: 'Shared cosmic moments deepen soul bonds',
    options: [
      {
        id: 'eclipse',
        text: 'Solar or lunar eclipse',
        description: 'Powerful transformation and new beginnings',
        icon: '🌘',
      },
      {
        id: 'meteor_shower',
        text: 'Meteor shower under starry skies',
        description: 'Wishes and dreams coming true',
        icon: '☄️',
      },
      {
        id: 'aurora',
        text: 'Northern lights dancing above',
        description: 'Magical, otherworldly connection',
        icon: '🌌',
      },
      {
        id: 'planetary_alignment',
        text: 'Rare planetary alignment',
        description: 'Perfect cosmic timing and harmony',
        icon: '🪐',
      },
    ],
  },
  {
    id: 18,
    type: 'intuition',
    question: 'Your heart whispers that your next great love will be...',
    subtitle: "Trust your inner knowing about love's nature",
    options: [
      {
        id: 'unexpected',
        text: 'Completely unexpected and surprising',
        description: 'Love arrives when you least expect it',
        icon: '🎁',
      },
      {
        id: 'familiar',
        text: 'Familiar, like coming home',
        description: 'Soul recognition and deep comfort',
        icon: '🏡',
      },
      {
        id: 'transformative',
        text: 'Transformative and life-changing',
        description: 'Love that revolutionizes your world',
        icon: '🦋',
      },
      {
        id: 'healing',
        text: 'Healing and deeply nurturing',
        description: 'Love that mends and strengthens',
        icon: '💚',
      },
    ],
  },
  {
    id: 19,
    type: 'timing',
    question: 'Which number sequence has been appearing in your life lately?',
    subtitle: 'Angel numbers carry messages about love timing',
    options: [
      {
        id: 'eleven_eleven',
        text: '11:11 - Gateway moments',
        description: 'Manifestation and wish fulfillment',
        icon: '✨',
      },
      {
        id: 'two_two_two',
        text: '222 - Balance and partnership',
        description: 'Harmony and relationship alignment',
        icon: '⚖️',
      },
      {
        id: 'three_three_three',
        text: '333 - Divine guidance',
        description: 'Spiritual support and protection',
        icon: '👼',
      },
      {
        id: 'five_five_five',
        text: '555 - Major life changes',
        description: 'Transformation and new opportunities',
        icon: '🔄',
      },
    ],
  },
  {
    id: 20,
    type: 'emotion',
    question:
      'When you imagine your wedding day (or commitment ceremony), what matters most?',
    subtitle: 'Your values shape your romantic destiny',
    options: [
      {
        id: 'intimate_connection',
        text: 'The intimate connection between you two',
        description: 'Deep bond and personal meaning',
        icon: '💕',
      },
      {
        id: 'celebration',
        text: 'Celebrating with loved ones',
        description: 'Community and shared joy',
        icon: '🎉',
      },
      {
        id: 'sacred_moment',
        text: 'The sacred, spiritual moment',
        description: 'Divine blessing and higher purpose',
        icon: '🙏',
      },
      {
        id: 'new_beginning',
        text: 'The promise of a beautiful future',
        description: 'Hope and exciting possibilities',
        icon: '🌅',
      },
    ],
  },
  {
    id: 21,
    type: 'astrology',
    question: 'Which gemstone calls to your romantic energy?',
    subtitle: 'Crystals amplify your love frequency',
    options: [
      {
        id: 'rose_quartz',
        text: 'Rose Quartz - unconditional love',
        description: 'Heart healing and self-love',
        icon: '💎',
      },
      {
        id: 'emerald',
        text: 'Emerald - heart chakra activation',
        description: 'Emotional balance and loyalty',
        icon: '💚',
      },
      {
        id: 'moonstone',
        text: 'Moonstone - intuitive connection',
        description: 'Psychic bonds and emotional depth',
        icon: '🌙',
      },
      {
        id: 'garnet',
        text: 'Garnet - passionate commitment',
        description: 'Devotion and lasting partnership',
        icon: '❤️',
      },
    ],
  },
  {
    id: 22,
    type: 'intuition',
    question:
      'In your heart of hearts, you know your next love will find you...',
    subtitle: "Your deepest knowing reveals love's arrival",
    options: [
      {
        id: 'when_ready',
        text: "When you're truly ready and healed",
        description: 'Perfect timing with inner preparation',
        icon: '🌱',
      },
      {
        id: 'unexpected_moment',
        text: 'In an unexpected, magical moment',
        description: 'Serendipity and divine orchestration',
        icon: '✨',
      },
      {
        id: 'following_passion',
        text: 'While following your passion',
        description: 'Aligned purpose attracts aligned love',
        icon: '🎯',
      },
      {
        id: 'letting_go',
        text: 'When you finally let go and trust',
        description: 'Surrender opens the heart to receive',
        icon: '🕊️',
      },
    ],
  },
  {
    id: 23,
    type: 'timing',
    question: 'Which life milestone are you most looking forward to?',
    subtitle: 'Future goals align with romantic timing',
    options: [
      {
        id: 'career_success',
        text: 'Achieving a major career goal',
        description: 'Professional fulfillment opens the heart',
        icon: '🏆',
      },
      {
        id: 'travel_adventure',
        text: 'A meaningful travel adventure',
        description: 'New experiences bring new connections',
        icon: '✈️',
      },
      {
        id: 'creative_project',
        text: 'Completing a creative project',
        description: 'Artistic expression attracts kindred souls',
        icon: '🎨',
      },
      {
        id: 'spiritual_growth',
        text: 'Deepening spiritual understanding',
        description: 'Inner development magnetizes conscious love',
        icon: '🧘',
      },
    ],
  },
  {
    id: 24,
    type: 'emotion',
    question:
      'As you complete this journey of self-reflection, how does your heart feel?',
    subtitle: "Your current state reveals love's proximity",
    options: [
      {
        id: 'open_excited',
        text: 'Open, excited, and ready',
        description: 'Perfect alignment for receiving love',
        icon: '💖',
      },
      {
        id: 'peaceful_trusting',
        text: 'Peaceful and trusting in divine timing',
        description: 'Surrender and faith attract miracles',
        icon: '🙏',
      },
      {
        id: 'curious_hopeful',
        text: 'Curious and hopeful about the future',
        description: 'Positive expectation magnetizes good',
        icon: '🌟',
      },
      {
        id: 'grateful_content',
        text: 'Grateful and content with your journey',
        description: 'Appreciation attracts more to appreciate',
        icon: '🌺',
      },
    ],
  },
]
