import jsPDF from 'jspdf'

export const generateQuizResultPDF = (
  userData: any,
  results: any,
  quizTitle: string,
  fullAnalysis: string
) => {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(75, 46, 131) // Purple color
  doc.text('QuizzAstrology.com', 20, 20)

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text(`${quizTitle} - Complete Results`, 20, 35)

  // User Information
  doc.setFontSize(12)
  doc.text(`Name: ${userData.fullName}`, 20, 55)
  doc.text(`Email: ${userData.email}`, 20, 65)
  doc.text(`Date of Birth: ${userData.dateOfBirth}`, 20, 75)
  doc.text(`Country: ${userData.country || userData.countryOfBirth}`, 20, 85)
  if (userData.city || userData.cityOfBirth) {
    doc.text(`City: ${userData.city || userData.cityOfBirth}`, 20, 95)
  }

  // Results
  doc.setFontSize(14)
  doc.setTextColor(75, 46, 131)
  doc.text('Your Results:', 20, 115)

  doc.setFontSize(11)
  doc.setTextColor(0, 0, 0)

  // Split long text into multiple lines
  const splitText = doc.splitTextToSize(fullAnalysis, 170)
  doc.text(splitText, 20, 130)

  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(10)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by QuizzAstrology.com', 20, pageHeight - 20)
  doc.text(
    `Generated on: ${new Date().toLocaleDateString()}`,
    20,
    pageHeight - 10
  )

  return doc
}
