export const tarotCards = [
  {
    name: "The Fool",
    symbol: "🃏",
    shortMeaning: "New beginnings, spontaneity, and infinite potential await you",
    element: "Air",
    keywords: ["new beginnings", "adventure", "potential", "innocence", "spontaneity"],
  },
  {
    name: "The Magician",
    symbol: "🎩",
    shortMeaning: "You have the power to manifest your dreams into reality",
    element: "Air",
    keywords: ["manifestation", "power", "skill", "concentration", "action"],
  },
  {
    name: "The High Priestess",
    symbol: "🌙",
    shortMeaning: "Trust your intuition and inner wisdom to guide you",
    element: "Water",
    keywords: ["intuition", "mystery", "subconscious", "wisdom", "spirituality"],
  },
  {
    name: "The Empress",
    symbol: "👑",
    shortMeaning: "Abundance, creativity, and nurturing energy surround you",
    element: "Earth",
    keywords: ["abundance", "creativity", "nurturing", "fertility", "nature"],
  },
  {
    name: "The Lovers",
    symbol: "💕",
    shortMeaning: "Important choices about love and relationships are before you",
    element: "Air",
    keywords: ["love", "relationships", "choices", "harmony", "attraction"],
  },
  {
    name: "The Chariot",
    symbol: "🏆",
    shortMeaning: "Victory through determination and willpower is yours",
    element: "Water",
    keywords: ["victory", "determination", "control", "success", "ambition"],
  },
  {
    name: "Strength",
    symbol: "🦁",
    shortMeaning: "Inner strength and courage will overcome all obstacles",
    element: "Fire",
    keywords: ["strength", "courage", "patience", "compassion", "inner power"],
  },
  {
    name: "The Hermit",
    symbol: "🕯️",
    shortMeaning: "Seek wisdom within and trust your inner guidance",
    element: "Earth",
    keywords: ["introspection", "wisdom", "guidance", "solitude", "enlightenment"],
  },
  {
    name: "The Wheel of Fortune",
    symbol: "🎡",
    shortMeaning: "Destiny and good fortune are turning in your favor",
    element: "Fire",
    keywords: ["destiny", "fortune", "cycles", "change", "opportunity"],
  },
  {
    name: "The Tower",
    symbol: "⚡",
    shortMeaning: "Sudden change will liberate you from limiting situations",
    element: "Fire",
    keywords: ["change", "revelation", "liberation", "breakthrough", "awakening"],
  },
  {
    name: "The Star",
    symbol: "⭐",
    shortMeaning: "Hope, healing, and divine guidance illuminate your path",
    element: "Air",
    keywords: ["hope", "healing", "guidance", "inspiration", "spirituality"],
  },
  {
    name: "The World",
    symbol: "🌍",
    shortMeaning: "Completion, success, and new adventures await you",
    element: "Earth",
    keywords: ["completion", "success", "achievement", "fulfillment", "wholeness"],
  },
]
